### PR TITLE
thermal crosstalk experiments

### PR DESCRIPTION
**Pull request by simbilod**
@joamatab are the design for testing written down somewhere? Need to check pad spacing, gc-pad spacing, and such. All easily changed

image

### CODE REVIEW

**Comment by simbilod** [comment]
@HelgeGehring

**Comment by HelgeGehring** [comment]
Looks great! Should we maybe submit the cell two or three times with different gaps?

**Comment by joamatab** [comment]
looks great Simon,

see [DFT rules here](https://docs.google.com/presentation/d/1_ppHYec6LydML4RMRJdNI4DXHb0hgW7znToQCGgSF6M/edit#slide=id.g1d30f86c8dc_0_11)

we need to label the GND and provide a YAML 

see [examples](https://github.com/SiEPIC/SiEPIC_EBeam_PDK/tree/master/Examples/thermo-optic)

@lukasc-ubc
@mustafacc

**Comment by lukasc-ubc** [comment]
@joamatab @HelgeGehring @simbilod 
I created a new merge system on the [edX page for the heater fabrication run](https://learning.edx.org/course/course-v1:UBCx+Phot1x+1T2023/block-v1:UBCx+Phot1x+1T2023+type@sequential+block@c7b757da56d4429ba8b853dc73dae16c/block-v1:UBCx+Phot1x+1T2023+type@vertical+block@51c1dbb8e96941b8af9dbf43ec8e5ee0).  I found your files and merged them.
Note that your metal contacts are not correctly defined.  the contacts are, from the top, G1, S1, G2, S2. This means if you have only one signal, you should use G1,S1, and they should be on a pitch of 125 µm.  Presently your pads are on a 200 µm pitch.
Your cell dimensions are also not correct.
Do you have access to the edX page?
image

**Comment by simbilod** [comment]
Hi @lukasc-ubc , I have revised the design according to these rules and dimensions :)

GCs that are part of the same measurement are separated by 127 um

image

**Comment by joamatab** [comment]
Hi Simon, the max number of gratings is 4, the laser is on the second from the top

**Comment by simbilod** [comment]
This is an array of gratings pairs that are 127um apart, it's just that I can only fit them interweaving like this

Can we not have more than 4 gratings total? The other masks in this repo all have multiple GC arrays

**Comment by joamatab** [comment]
the layout looks pretty cool,

see [links](https://docs.google.com/document/d/17hK5VDT2SmJxKsRDCuxHsrDun3E9itWlhGKzu11pMnQ/edit) and [dft rules here](https://docs.google.com/presentation/d/17FWUaRZ0zKV5zrPgY4fo98M8ywtmE3blaxkwUvk_7yM/edit#slide=id.g207b302f043_0_0)

**Comment by simbilod** [comment]
Ok I am just seeing the labels slides for the first time [(these ones)](https://docs.google.com/presentation/d/1iAW_SBCXS2rSzv9wnU96NacFfh2k2fV6GYP3ctvNx5A/edit?pli=1#slide=id.g1bab15af34a_2_227)

Can we associate one electrical bondpad with multiple optical experiments? I would like to see the optical transfer function of different rings (which would all appear as different opt_<polarization>_<wavelength>_<device-class>_<unique-device-id>) as a single heater is swept

@joamatab @lukasc-ubc

**Comment by simbilod** [comment]
can I just put a bunch of labels with different strings at the same location?

**Comment by lukasc-ubc** [comment]
You have an interesting idea.  I think this should work as follows:

1. Each optical circuit is connected to up to 4 GCs
2. many circuits can be interleaved as you've done
3. <deviceID> values need to be unique, one per optical circuit
4. I think you could have multiple electrical labels on the same metal contact refering to the <deviceID>

The measurement will then run the heater multiple times, each time measuring the optical spectrum of one of the rings.

This is a great way to do it.  I like it.

Also, please feel free to submit many cells.  We have room ;)

You might want to make variations where you have the heater ring in the middle, and some test rings above, and some test rings below. That way you get two data points for each ∆y value.

Would also be interesting to see what happens if you cover the rings with the metal wire.  How much thermal cross-talk does metal introduce?

This will be an interesting study, and hopefully you can get many measurements.

image

**Pull request merged**
